# Generated by Django 6.0a1 on 2025-10-02 01:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prouct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('category', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField())),
            ],
        ),
    ]
