# Generated by Django 6.0a1 on 2025-10-02 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prouct',
            new_name='Product',
        ),
    ]
