# Generated by Django 5.2.7 on 2025-10-02 07:42

from django.db import migrations

def initialize_data(apps, schema_editor):
    Category = apps.get_model('listings', 'Category')
    Tag = apps.get_model('listings', 'Tag')
    Product = apps.get_model('listings', 'Product')

    if Category.objects.count() == 0:
        cat1 = Category.objects.create(name='Tops')
        cat2 = Category.objects.create(name='Pants')
        cat3 = Category.objects.create(name='Sweaters')
        cat4 = Category.objects.create(name='Dresses')
        cat5 = Category.objects.create(name='Coats')


    if Tag.objects.count() == 0:
        tag1 = Tag.objects.create(name='Black')
        tag2 = Tag.objects.create(name='White')
        tag3 = Tag.objects.create(name='Grey')
        tag4 = Tag.objects.create(name='Beige')
        tag5 = Tag.objects.create(name='Red')
        tag6 = Tag.objects.create(name='Orange')
        tag7 = Tag.objects.create(name='Yellow')
        tag8 = Tag.objects.create(name='Green')
        tag9 = Tag.objects.create(name='Blue')
        tag10 = Tag.objects.create(name='Purple')
        
    if Product.objects.count() == 0:
        product1 = Product.objects.create(
            name='Tops-1',
            description='A black and grey top.',
            category=cat1,
        )
        product1.tags.set([tag1, tag3])

        product2 = Product.objects.create(
            name='Tops-2',
            description='A white and grey top.',
            category=cat1,
        )
        product2.tags.set([tag2, tag3])

        product3 = Product.objects.create(
            name='Tops-3',
            description='A white and beige top.',
            category=cat1,
        )
        product3.tags.set([tag2, tag4])

        product4 = Product.objects.create(
            name='Tops-4',
            description='A red top.',
            category=cat1,
        )
        product4.tags.set([tag5])

        product5 = Product.objects.create(
            name='Tops-5',
            description='A purple top.',
            category=cat1,
        )
        product5.tags.set([tag10])

        product6 = Product.objects.create(
            name='Pants-1',
            description='An orange pant.',
            category=cat2,
        )
        product6.tags.set([tag6])

        product7 = Product.objects.create(
            name='Pants-2',
            description='A yellow and green pant.',
            category=cat2,
        )
        product7.tags.set([tag7, tag8])

        product8 = Product.objects.create(
            name='Pants-3',
            description='An orange pant.',
            category=cat2,
        )
        product8.tags.set([tag6])

        product9 = Product.objects.create(
            name='Pants-4',
            description='A yellow pant.',
            category=cat2,
        )
        product9.tags.set([tag7])

        product10 = Product.objects.create(
            name='Pants-5',
            description='A blue pant.',
            category=cat2,
        )
        product10.tags.set([tag9])

        product11 = Product.objects.create(
            name='Sweaters-1',
            description='A black, grey and red sweater.',
            category=cat3,
        )
        product11.tags.set([tag1, tag3, tag5])

        product12 = Product.objects.create(
            name='Sweaters-2',
            description='A white, beige and orange sweater.',
            category=cat3,
        )
        product12.tags.set([tag2, tag4, tag6])

        product13 = Product.objects.create(
            name='Sweaters-3',
            description='A yellow and blue sweater.',
            category=cat3,
        )
        product13.tags.set([tag7, tag9])

        product14 = Product.objects.create(
            name='Sweaters-4',
            description='A green and purple sweater.',
            category=cat3,
        )
        product14.tags.set([tag8, tag10])

        product15 = Product.objects.create(
            name='Sweaters-5',
            description='An white, grey and red sweater.',
            category=cat3,
        )
        product15.tags.set([tag2, tag3, tag5])

        product16 = Product.objects.create(
            name='Dresses-1',
            description='A black, white and green dress.',
            category=cat4,
        )
        product16.tags.set([tag1, tag2, tag8])

        product17 = Product.objects.create(
            name='Dresses-2',
            description='A white, beige and green dress.',
            category=cat4,
        )
        product17.tags.set([tag2, tag4, tag8])

        product18 = Product.objects.create(
            name='Dresses-3',
            description='A grey, orange and blue dress.',
            category=cat4,
        )
        product18.tags.set([tag3, tag6, tag9])

        product19 = Product.objects.create(
            name='Dresses-4',
            description='A white, red and purple dress.',
            category=cat4,
        )
        product19.tags.set([tag2, tag5, tag10])

        product20 = Product.objects.create(
            name='Dresses-5',
            description='A red, orange and blue dress.',
            category=cat4,
        )
        product20.tags.set([tag5, tag6, tag9])

        product21 = Product.objects.create(
            name='Coats-1',
            description='A black, white and grey coat.',
            category=cat5,
        )
        product21.tags.set([tag1, tag2, tag3])
        
        product22 = Product.objects.create(
            name='Coats-2',
            description='A beige and red coat.',
            category=cat5,
        )
        product22.tags.set([tag4, tag5])

        product23 = Product.objects.create(
            name='Coats-3',
            description='A white and beige coat.',
            category=cat5,
        )
        product23.tags.set([tag2, tag4])

        product24 = Product.objects.create(
            name='Coats-4',
            description='A yellow green and purple coat.',
            category=cat5,
        )
        product24.tags.set([tag7, tag8, tag10])

        product25 = Product.objects.create(
            name='Coats-5',
            description='A black coat.',
            category=cat5,
        )
        product25.tags.set([tag1])



class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_category_tag_alter_product_name_remove_product_tags_and_more'),
    ]

    operations = [
        migrations.RunPython(initialize_data),
    ]
